# coding: utf-8

"""
    マネーフォワード クラウド経費API

    このページは[マネーフォワード クラウド経費](https://expense.moneyforward.com)（クラウド型の経費精算・ワークフローサービス）のAPIドキュメントです。ご利用開始の手順については、[github](https://github.com/moneyforward/expense-api-doc) をご覧ください。バグ報告や改善要望はgithub上からissue登録をして頂ければ幸いです。このドキュメントは[Swagger](http://swagger.io)の仕様で作成されています。実際にこのページでAPIの試打を行うことができます。試打を行いたい場合は、APIを利用するアプリケーションの登録の際に、Redirect URIを`https://expense.moneyforward.com/api/oauth2-redirect.html`に指定してお試しください。  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mfexapiclient
from mfexapiclient.api.office_member_api import OfficeMemberApi  # noqa: E501
from mfexapiclient.rest import ApiException


class TestOfficeMemberApi(unittest.TestCase):
    """OfficeMemberApi unit test stubs"""

    def setUp(self):
        self.api = mfexapiclient.api.office_member_api.OfficeMemberApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_office_member(self):
        """Test case for create_office_member

        メンバーを追加する  # noqa: E501
        """
        pass

    def test_destroy_office_member(self):
        """Test case for destroy_office_member

        メンバーを削除する  # noqa: E501
        """
        pass

    def test_destroy_reimburse_bank_account(self):
        """Test case for destroy_reimburse_bank_account

        メンバーの振込口座を削除する  # noqa: E501
        """
        pass

    def test_find_office_member(self):
        """Test case for find_office_member

        事業所に所属するメンバーを返す  # noqa: E501
        """
        pass

    def test_find_office_members(self):
        """Test case for find_office_members

        事業所に所属するメンバー一覧を返す  # noqa: E501
        """
        pass

    def test_save_reimburse_bank_account(self):
        """Test case for save_reimburse_bank_account

        メンバーの振込口座を登録／更新する  # noqa: E501
        """
        pass

    def test_update_office_member(self):
        """Test case for update_office_member

        メンバーを更新する  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
